name: ERC721-Linkable Build-Test

on:
    pull_request:
        branches:
          - develop

jobs:
    ############ BUILD PACKAGE ############
    # build-package:
    #     name: Build Package
    #     runs-on: ubuntu-latest
    #     needs:
    #         - test-unit
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v3

    #         - name: Setup Node
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: 16.x
    #               cache: 'npm'
    #               registry-url: https://registry.npmjs.org/

    #         - run: corepack enable

    #         - name: Install NPM Dependencies
    #           run: npm install --immutable --network-timeout 300000

    #         - name: Build Package
    #           run: npm build

    #         - name: Build Eslint rules
    #           run: yarn lint:fix

    ############ UNIT TEST ############
    test-unit:
        name: Unit Tests
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node: 18
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: 'npm'
                  registry-url: https://registry.npmjs.org/

            - run: corepack enable

            - name: Install NPM Dependencies
              run: npm install 

            - name: Unit Tests
              run: ./node_modules/.bin/cross-env MRC_BLOCKNUMBER=${{ secrets.MRC_BLOCKNUMBER }} ALCHEMY_POLYGON=${{ secrets.ALCHEMY_POLYGON }} npx hardhat test